In [1]:
import pandas as pd

df = pd.read_csv("https://data.lacity.org/api/views/y8tr-7khq/rows.csv?accessType=DOWNLOAD")
df.columns

0          (33.9829, -118.3338)
1          (34.0454, -118.3157)
2           (33.942, -118.2717)
3          (33.9572, -118.2717)
4          (34.2009, -118.6369)
5          (34.0591, -118.2412)
6          (34.1211, -118.2048)
7           (34.241, -118.3987)
8          (34.3147, -118.4589)
9          (34.2012, -118.4662)
10         (34.2354, -118.4517)
11         (34.0294, -118.2671)
12         (33.9651, -118.2783)
13         (33.9651, -118.2754)
14          (34.2012, -118.416)
15         (33.9456, -118.2652)
16         (34.0431, -118.2536)
17         (34.0503, -118.2504)
18         (34.0352, -118.2583)
19          (34.048, -118.2577)
20           (34.045, -118.264)
21          (34.0407, -118.268)
22         (34.0423, -118.2452)
23         (34.0517, -118.2456)
24         (34.0435, -118.2471)
25         (34.0395, -118.2656)
26         (34.2139, -118.4793)
27         (34.0581, -118.2371)
28         (34.0688, -118.2333)
29         (34.0482, -118.2472)
                   ...
1621408    (34.1595, -118.6121)
1621409    (34.2048, -118.6203)
1621410    (34.2047, -118.5994)
1621411    (34.1733, -118.5974)
1621412     (34.212, -118.5754)
1621413    (34.2143, -118.6206)
1621414    (34.1992, -118.5885)
1621415    (34.1683, -118.6007)
1621416    (34.1793, -118.6002)
1621417     (34.201, -118.5885)
1621418    (34.2083, -118.6103)
1621419    (34.1829, -118.6077)
1621420    (34.1752, -118.6548)
1621421      (34.232, -118.608)
1621422    (34.1968, -118.5847)
1621423    (34.1591, -118.6222)
1621424    (34.1805, -118.5975)
1621425    (34.1866, -118.6428)
1621426    (34.1802, -118.6147)
1621427    (34.1883, -118.6274)
1621428    (34.2029, -118.5955)
1621429     (34.176, -118.5724)
1621430    (34.2156, -118.5809)
1621431     (34.201, -118.5943)
1621432    (34.2047, -118.5688)
1621433    (34.1649, -118.6027)
1621434    (34.1923, -118.6104)
1621435    (34.1883, -118.6274)
1621436    (34.1905, -118.6059)
1621437     (34.232, -118.6006)
Name: Location , Length: 1621438, dtype: object